name: build-cron
on:
  schedule:
    - cron: '35 18 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: timestamp
        run: date
      - name: build
        run: |
          curl \
          --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_MQlxIz5zQP4GMibWntBaE9r3ws4B/zrVrtysmCF' \
