name: build-cron
on:
  schedule:
    - cron: '25 18 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date
          curl \
          --request POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_MQlxIz5zQP4GMibWntBaE9r3ws4B/zrVrtysmCF' \
