name: Shrink PDFs
on:
  pull_request:
    branches: [main]
jobs:
  shrinkPDFs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ghostscript
        run: sudo apt-get install ghostscript
      - name: Shrink PDFs
        run: |
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          ./scripts/shrink-pr-pdfs/shrink-pr-pdfs.sh "$PR_URL"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: shrink PDFs"
