name: build and test
on: pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: "7"
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@mauriciorobayo"
      - run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: pnpm rebuild && pnpm prepare --if-present
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ci
