name: trigger-deploy-hook
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  trigger-deploy-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hit build endpoint
        run: node ./scripts/exponential-retry-back-off.js
