name: trigger-deploy-hook
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  trigger-deploy-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@mauriciorobayo"
          cache: "pnpm"
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: node ./scripts/exponential-retry-back-off.js ${{ secrets.VERCEL_DEPLOYMENT_HOOK }}
