name: trigger-deploy-hook
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  trigger-deploy-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        npm ci --ignore-scripts
        node ./scripts/exponential-retry-back-off.js
